name: 🌟 Feature request
description: Suggest a feature to improve Yōkai
labels: [enhancement]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      description: How can Yōkai be improved?
      placeholder: |
        Example:
          "It should work like this..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
          required: true
        - label: If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
          required: true
        - label: I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
          required: true
        - label: I have checked through the app settings for my feature.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
